data_dir: /Volumes/L96/DRL/days/
ent_coef: 0.002
epochs: 30
eval_runs_per_env: 1
gamma: 0.99
grad_clip: 0.5
last_n_ticks: 10
lr: 0.00032
net_arch:
- 64
- 64
resample: false
rescale: true
seed: 3538
snapshot_size: 5000
snapshots_per_day: 3
start_end_clip: 0
tag: null
tot_snapshots: 25
use_m_t_m: true
